Add Verilog backend

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -55,6 +55,9 @@ Supported targets:
   x86_64-bsd           (x86 64 bits, BSD)
   x86_64-macosx        (x86 64 bits, MacOS X)
   x86_64-cygwin        (x86 64 bits, Cygwin environment under Windows)
+  verilog-linux        (x86 64 bits, Linux)
+  verilog-bsd          (x86 64 bits, BSD)
+  verilog-macosx       (x86 64 bits, MacOS X)
   rv32-linux           (RISC-V 32 bits, Linux)
   rv64-linux           (RISC-V 64 bits, Linux)
   aarch64-linux        (AArch64, i.e. ARMv8 in 64-bit mode, Linux)
@@ -175,6 +178,8 @@ case "$target" in
       arch="x86"; model="32sse2"; endianness="little"; bitsize=32;;
   x86_64-*|amd64-*)
       arch="x86"; model="64"; endianness="little"; bitsize=64;;
+  verilog-*)
+      arch="verilog"; model="32"; endianness="little"; bitsize=64;;
   powerpc-*|ppc-*)
       arch="powerpc"; model="ppc32"; endianness="big"; bitsize=32;;
   powerpc64-*|ppc64-*)
@@ -399,6 +404,55 @@ if test "$arch" = "x86" -a "$bitsize" = "64"; then
         cprepro_options="-std=c99 -m64 -U__GNUC__ '-D__attribute__(x)=' -E"
         libmath="-lm"
         system="cygwin"
+        ;;
+    *)
+        echo "Error: invalid eabi/system '$target' for architecture X86_64." 1>&2
+        echo "$usage" 1>&2
+        exit 2;;
+  esac
+fi
+
+if test "$arch" = "verilog" -a "$bitsize" = "64"; then
+
+  case "$target" in
+    bsd)
+        abi="standard"
+        casm="${toolprefix}gcc"
+        casm_options="-m64 -c"
+        cc="${toolprefix}gcc -m64"
+        clinker="${toolprefix}gcc"
+        clinker_options="-m64"
+        cprepro="${toolprefix}gcc"
+        cprepro_options="-std=c99 -m64 -U__GNUC__ -E"
+        libmath="-lm"
+        system="bsd"
+        ;;
+    linux)
+        abi="standard"
+        casm="${toolprefix}gcc"
+        casm_options="-m64 -c"
+        cc="${toolprefix}gcc -m64"
+        clinker="${toolprefix}gcc"
+        clinker_options="-m64"
+        cprepro="${toolprefix}gcc"
+        cprepro_options="-std=c99 -m64 -U__GNUC__ -E"
+        libmath="-lm"
+        system="linux"
+        ;;
+    macosx)
+        # kernel major versions count upwards from 4 for OSX 10.0 to 15 for OSX 10.11
+        kernel_major=`uname -r | cut -d "." -f 1`
+
+        abi="macosx"
+        casm="${toolprefix}gcc"
+        casm_options="-arch x86_64 -c"
+        cc="${toolprefix}gcc -arch x86_64"
+        clinker="${toolprefix}gcc"
+        clinker_needs_no_pie=false
+        cprepro="${toolprefix}gcc"
+        cprepro_options="-std=c99 -arch x86_64 -U__GNUC__ -U__clang__ -U__BLOCKS__ '-D__attribute__(x)=' '-D__asm(x)=' '-D_Nullable=' '-D_Nonnull=' -E"
+        libmath=""
+        system="macosx"
         ;;
     *)
         echo "Error: invalid eabi/system '$target' for architecture X86_64." 1>&2
